# -*- mode: ruby -*-
# vi: set ft=ruby :  

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  
  config.vm.provider "virtualbox" do |v|
    v.name = "saltik"
    v.memory = 1024
    v.cpus = 2
  end
  config.vm.synced_folder "../", "/opt/vagrant"
  config.vm.synced_folder "salt/roots/", "/srv/"

  config.vm.provision :salt do |salt|
    salt.minion_config = 'salt/minion'
    salt.run_highstate = true

#  salt.pillar({"projectName" => "demostand"})
  end
end

